dist: trusty
sudo: false
os:
  - linux

cache:
  directories:
    - '$HOME/.sonar/cache'

before_script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")

install:  
    - nvm install node
    - npm install
    - npm install -g coveralls

script:
    - nvm use node
    - npm run lint
    - npm run test-dev  

after_success:
    - coveralls < .coverage/unit/lcov.info