dist: trusty
sudo: false
os:
- linux

cache:
  directories:
    - '$HOME/.sonar'
    - 'node_modules'

before_script:
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")

install:  
    - nvm install node
    - npm install
    - npm install -g coveralls sonarqube-scanner

script:
    - nvm use node
    - npm run lint
    - npm run test-dev  
    - sonar-scanner -Dsonar.projectVersion=$PROJECT_VERSION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN

after_success:
    - coveralls < .coverage/lcov.info